name: Deploy to Staging
on:
  push:
    branches: [ staging ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DIR_NAME: senikma-php-2024
  DOCKER_IMAGE: 3csdesign/freudenberg-php-2023:staging

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Move Files"
        run: |
          rm app/config/config.php
          rm app/public_html/top.php
          mv live-config/staging/top.php app/public_html/top.php
          mv live-config/staging/global-config.php app/config/config.php

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  copy-files:
    runs-on: ubuntu-latest
    needs: docker-image-build
    steps:
      - name: Checkout Staging Branch
        uses: actions/checkout@v2
        with:
          ref: staging
          path: staging # Set the path to a subdirectory

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.HELIOS_SSH_KEY }}

      - name: Zip App Directory
        run: |
          cd staging
          zip -r app.zip app

      - name: Copy Zip File to Remote Server
        run: |
          scp -o StrictHostKeyChecking=no staging/app.zip ${{ secrets.HELIOS_SSH_USER }}@${{ secrets.HELIOS_SSH_HOST }}:/priv-app/${{ env.DIR_NAME }}/release/
          scp -o StrictHostKeyChecking=no staging/live-config/staging/docker-compose.yml ${{ secrets.HELIOS_SSH_USER }}@${{ secrets.HELIOS_SSH_HOST }}:/priv-app/${{ env.DIR_NAME }}/config/
          scp -o StrictHostKeyChecking=no staging/live-config/staging/global-config.php ${{ secrets.HELIOS_SSH_USER }}@${{ secrets.HELIOS_SSH_HOST }}:/priv-app/${{ env.DIR_NAME }}/config/
          scp -o StrictHostKeyChecking=no staging/live-config/staging/top.php ${{ secrets.HELIOS_SSH_USER }}@${{ secrets.HELIOS_SSH_HOST }}:/priv-app/${{ env.DIR_NAME }}/config/
    
      - name: Clean Up
        run: rm staging/app.zip


  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: copy-files
    steps:
      - name: Deployment command Runner
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.HELIOS_SSH_HOST }}
         username: ${{ secrets.HELIOS_SSH_USER }}
         key: ${{ secrets.HELIOS_SSH_KEY }}
         port: 22
         script: |
          
          /priv-app/${{ env.DIR_NAME }}/config/deploy.sh
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/${{ env.DOCKER_IMAGE }}
          docker-compose -f /priv-app/${{ env.DIR_NAME }}/config/docker-compose.yml up -d
