---
- name: Update Cloudflare DNS records
  hosts: localhost
  gather_facts: no
  vars:
    cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
    # cloudflare_account_email: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_EMAIL') }}"
    # cloudflare_account_api_key: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_API_KEY') }}"
  tasks:
    # - name: Create a test.example.net A record to point to 127.0.0.1
    #   community.general.cloudflare_dns:
    #     zone: example.net
    #     record: test
    #     type: A
    #     value: 127.0.0.1
    #     account_email: "{{ cloudflare_account_email }}"
    #     account_api_key: "{{ cloudflare_account_api_key }}"
    #   register: record

    - name: Create a record using API token
      community.general.cloudflare_dns:
        zone: itsnooblk.xyz
        proxied: true
        record: test
        type: A
        value: 143.32.3.33
        api_token: "{{ cloudflare_api_token }}"
        state: present
        solo: true