---
   - name: Update Cloudflare DNS records
     hosts: local
     gather_facts: no
     vars_files:
       - ../vars/main.yml
     tasks:
       - name: Create a test.example.net A record to point to 127.0.0.1
         community.general.cloudflare_dns:
           zone: example.net
           record: test
           type: A
           value: 127.0.0.1
           account_email: "{{ cloudflare_account_email }}"
           account_api_key: "{{ cloudflare_account_api_key }}"
         register: record

       - name: Create a record using API token
         community.general.cloudflare_dns:
           zone: example.net
           record: test
           type: A
           value: 127.0.0.1
           api_token: "{{ cloudflare_api_token }}"

       - name: Create an example.net CNAME record to example.com
         community.general.cloudflare_dns:
           zone: example.net
           type: CNAME
           value: example.com
           account_email: "{{ cloudflare_account_email }}"
           account_api_key: "{{ cloudflare_account_api_key }}"
           state: present